spring:
  cloud:
    config:
      uri: http://localhost:8888  # Adresse du serveur Config
      fail-fast: true            # Option pour forcer l'échec si le serveur n'est pas accessible
  application:
    name: patient-service

