spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/facturation-db?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
