spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/traitement-db?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
