server:
  port: 9999
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: spring.cloud.config.server.git.uri=https://github.com/mohamedYoussfi/config-ecom-app
